# Site settings
title: Today I Learned
description: >
  Microblog of something technical I learned today.
baseurl: ""
url: "http://til.maltson.com"
twitter_username: amaltson
github_username:  amaltson

# Build settings
markdown: kramdown

gems: ['octopress-genesis-theme','jekyll-twitter-plugin']
